name: Run Tests

on:
  push:
    paths:
      - 'include/**'
      - 'source/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'include/**'
      - 'source/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Test Deps
      run:  sudo apt-get install -y libboost-test-dev

    - name: Make build files.
      run: |
        mkdir build && cd build
        cmake -DENABLE_TESTS=ON ..

    - name: Build and Install
      run: sudo cmake --build build --target install

    - name: Run LdConfig
      run: sudo ldconfig

    - name: Test
      run: |
        cd build
        ctest -VV
